name: Demo workflow
on: workflow_dispatch
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print console
        run: echo Hello Actions!
      - name: Print few lines
        run: |
          echo first line
          echo second line
          
